# Использование команд библиотеки NumPy

In [49]:
import numpy as np

## Создайте одномерный массив my_array, в котором по порядку все числа до 100, кратные 5

In [50]:
my_array = np.arange(5, 101, 5)
print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


## Из полученного массива получить массив с кратными 10 числами

In [62]:
my_array_10 = my_array[my_array % 10 == 0]
my_array_5 = my_array = my_array[my_array % 10 != 0]
print (my_array_10)
print(my_array_5)

[ 10  20  30  40  50  60  70  80  90 100]
[ 5 15 25 35 45 55 65 75 85 95]


## Получить двумерный массив с двумя столбцами

In [65]:
two_column_array = np.column_stack((my_array_5, my_array_10))
print(two_column_array)

[[  5  10]
 [ 15  20]
 [ 25  30]
 [ 35  40]
 [ 45  50]
 [ 55  60]
 [ 65  70]
 [ 75  80]
 [ 85  90]
 [ 95 100]]


## Получите набор my_second_array, в котором все элементы меньше предыдущего исходного на 5

In [70]:
my_second_array=two_column_array-5
print(my_second_array)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]
 [70 75]
 [80 85]
 [90 95]]


## Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте .T для транспонирования матрицы. 

In [71]:
combined_array = np.hstack((two_column_array, my_second_array.reshape(-1, 1))).T
print (combined_array)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 10 and the array at index 1 has size 20

In [ ]:
two_column_array = np.column_stack((my_array, my_array_10))

# Использование библиотеки Pandas

In [3]:
import pandas as pd
import openpyxl

## Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.

In [4]:
gbt=pd.read_csv('Global Population Trends(2016-2022).csv')
gbt

Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
0                    55            63.0      37.342       7.027   
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
...                 ...             ...         ...         ...   
1068                 38            61.0      32.516       8.266   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
0             5.129                  49.4           -  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
...             ...                   ...         ...  
1068          3.706                  39.5           -  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[1073 rows x 12 columns]

##  Считайте несколько первых записей таблицы (head())

In [55]:
gbt.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

## Определите размерность данного фрейма (shape)

In [60]:
print(gbt.shape)

(1073, 12)


## Выведите название заголовков столбцов фрейма (columns)

In [63]:
gbt.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

## Получите описание всех переменных (полей) (info())

In [65]:
gbt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


##  Удалите строки, не содержащие значения в столбце «Total Population» - “-” 

In [33]:
gbt1=gbt[gbt['Total Population']!='-']
print(gbt1.shape)
pd.options.mode.chained_assignment = None
gbt1.loc[:, 'Total Population'] = gbt1['Total Population'].str.replace(',', '')

gbt1['Total Population'] = gbt1['Total Population'].astype(int)

(864, 12)


## Получите описательную статистику по переменным (например, max(), min(), describe())

In [35]:
gbt1.max()

Country                    Zimbabwe
Year                           2021
Total Population         1412360000
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object

In [77]:
gbt1.min()

Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population                   -
Population Density                 -
Life Expectancy                    -
Birth Rate                       0.0
Death Rate                       0.0
Fertility Rate                     -
Infant Mortality Rate              -
Growth Rate                     -1.0
dtype: object

In [43]:
gbt1.describe()

Year  Total Population  Birth Rate  Death Rate
count   864.000000      8.640000e+02  864.000000  864.000000
mean   2019.500000      3.577942e+07   18.548384    7.889123
std       1.118682      1.393935e+08    9.887518    3.041385
min    2018.000000      1.086500e+04    0.000000    0.000000
25%    2018.750000      7.771928e+05   10.500000    6.116500
50%    2019.500000      6.332328e+06   15.628500    7.453500
75%    2020.250000      2.499417e+07   25.565000    9.385000
max    2021.000000      1.412360e+09   46.127000   21.700000

## Выполните сортировку данных по нескольким критериям

In [45]:
sortedGbt = gbt1.sort_values(by=['Year', 'Total Population'], ascending=[False, False])
sortedGbt.head()

Country  Year  Total Population Urban Population Rural Population  \
205           China  2021        1412360000      882,894,483      529,465,517   
435           India  2021        1407563842      498,179,071      909,384,771   
1022  United States  2021         332031554      275,164,510       56,867,044   
440       Indonesia  2021         273753191      156,833,203      116,919,988   
728        Pakistan  2021         231402117       86,636,953      144,765,164   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
205                   -            78.0       7.520       7.180   
435                   -            67.0      16.419       9.448   
1022                  -            76.0      11.000      10.400   
440                   -            68.0      16.425      10.065   
728                   -            66.0      27.519       7.168   

     Fertility Rate Infant Mortality Rate Growth Rate  
205           1.164                   5.1         0.0  
435           2.031                  25.5         1.0  
1022          1.664                   5.4         0.0  
440           2.175                  18.9         1.0  
728            3.47                  52.8         2.0

## Выведите название страны, которая имеет максимальную численность населения

In [47]:
max_population_country = sortedGbt.iloc[0]['Country']
print(max_population_country)

China


## Выведите название страны, которая имеет минимальную численность населения

In [46]:
min_population_country = sortedGbt.iloc[-1]['Country']
print(min_population_country)

Tuvalu


## Экспорт фрейма в MS Excel

In [30]:
gbt1.to_excel("Global_Population_Trends.xlsx", index=False, engine='openpyxl')